### ISSUE TITLE
Tracing hanging after clicking randomly on cancel button

### ISSUE THREAD

**Issue by talapadi** [chimple/chimple#1136]

**Comment by vineet32** [comment]
Before tracing on letter if we keep clicking on cancel button the tracing thing will start flickering.

https://user-images.githubusercontent.com/67994324/109124464-f4152100-7770-11eb-91c7-d272179e2e88.mp4


https://user-images.githubusercontent.com/67994324/109124518-042d0080-7771-11eb-835f-e7b421822e9f.mp4

**Comment by vineet32** [comment]
After tracing half of the letter & clicking on undo option the help animation is flickering
https://user-images.githubusercontent.com/67994324/109286556-61e04c00-7848-11eb-827e-c4b231d92053.mp4
