### ISSUE TITLE
After app launch, first time, hanging on clicking Hindi as language

### ISSUE THREAD

**Issue by talapadi** [chimple/chimple#1137]
Only on Rani's mobile
[1st page right click.txt](https://github.com/chimple/chimple/files/6035820/1st.page.right.click.txt)

**Comment by RakshithAcharya-art** [comment]
![Screenshot (263)](https://user-images.githubusercontent.com/62738256/109042842-a8be2c80-76f6-11eb-9494-269866d12cec.png)
![Screenshot (264)](https://user-images.githubusercontent.com/62738256/109042874-b07dd100-76f6-11eb-8f95-6741e79ab8f3.png)

![Screenshot (262)](https://user-images.githubusercontent.com/62738256/109042794-993ee380-76f6-11eb-94dd-1e309749a283.png)
