### ISSUE TITLE
Example : In addition (plus 1), the asseemnet was for (plus 3), in plus 2 level as well the assessment was testing for plus 3...

### ISSUE THREAD

**Issue by talapadi** [chimple/chimple#1168]

**Comment by faridarizwan** [comment]
This issues must be the one our QA team reported earlier. The quiz questions for numbers is for greater number than the number being taught for the lesson.

**Comment by Kiranks05** [comment]
![Screenshot_2021-03-17-15-22-45-140_org chimple bahama](https://user-images.githubusercontent.com/57090054/111452597-b20c4900-8738-11eb-94e5-d420b77dc658.jpg)

**Comment by Sutara-Skanda** [comment]
**I think we need to fix in code**

![Screenshot (56)](https://user-images.githubusercontent.com/62737989/112863923-fb637d80-90d4-11eb-99a5-d60ad8184bd6.png)
![Screenshot (58)](https://user-images.githubusercontent.com/62737989/112863951-01f1f500-90d5-11eb-9c6b-afe9b55db4fc.png)
![Screenshot (57)](https://user-images.githubusercontent.com/62737989/112863968-05857c00-90d5-11eb-9b95-6bdd5b4f4e02.png)

**Comment by Kiranks05** [comment]
The Duplication is happening in Quiz Questions
