### ISSUE TITLE
Hanging issue in Rewards screen

### ISSUE THREAD

**Issue by vineet32** [chimple/chimple#1335]
Just screen gets struck (not able to click any buttons)

**Comment by RakshithAcharya-art** [comment]
![FirstRewardScreen (2)](https://user-images.githubusercontent.com/62738256/118908413-0604fb00-b93f-11eb-8481-1f740a318d60.png)
![FontChangedWhenBackground](https://user-images.githubusercontent.com/62738256/118908438-14531700-b93f-11eb-89e4-3496d18200a0.png)

**Comment by RakshithAcharya-art** [comment]
Here font gets changed whenever the other button in the tab is clicked, and the font change is because of change of color of the chimple label that is used  highlight the selected one. It can be fixed by highlighting only the icons as below.

**Comment by RakshithAcharya-art** [comment]
![Uploading newRewardTabButton.png…]()

**Comment by RakshithAcharya-art** [comment]
![newRewardTabButton](https://user-images.githubusercontent.com/62738256/118908847-c1c62a80-b93f-11eb-9519-a9bc2818a909.png)
