### ISSUE TITLE
The Assessment is still appearing after completing it

### ISSUE THREAD

**Issue by Kiranks05** [chimple/chimple#1397]
Assessment  by the teacher which is still appearing in the Page after completing it.![2021-06-23_18h03_12.png](https://images.zenhubusercontent.com/60d313d5133f0eecc9365236/231c5ed2-de9d-422d-868d-8cd61f0c0de9)

**Comment by talapadi** [comment]
1. I assigned the assessment to user Sunita
2. On the Chimple Kids app, Sunita saw the Quiz in the Homework
3. Sunita completed Assessment Quiz
4. On the teacher app I can see that Sunita has completed
5. On the Kids app, the Assessment Quiz is not appearing in the Homework
