### ISSUE TITLE
Show school mode students in alphabetical order

### ISSUE THREAD

**Issue by talapadi** [chimple/chimple#1408]
@talapadi commented on [Mon Jun 28 2021](https://github.com/chimple/malta/issues/1203)

**Comment by Kiranks05** [comment]
still students list is not showing in![Screenshot_2021-07-02-11-45-58-585_org.chimple.bahama.jpg](https://images.zenhubusercontent.com/60d313d5133f0eecc9365236/d346327c-eb9d-435c-8ec0-044ef6b7def7) alphabetical order
