### ISSUE TITLE
Selectively push HotUpdate for testing

### ISSUE THREAD

**Issue by talapadi** [chimple/chimple#1746]

**Comment by vkamath16** [comment]
Pramond to add comments

**Comment by Pramodmarssun** [comment]
1. After installing the hot-update apk we have to create a debug15 profile and an Installation and creating profile was successful
2. We have to click on parent control and we have to go settings there we will get a text bar to write a server link after entering server link we have to click on update and the link will be updated. This is working
3. To reflect these changes we have to restart the app. After restarting it will update the link and its working fine.
4. Once we reopen the apk we will get the current version number of hot-update. its working fine 
5. Here we can play a lesson and its working 

Note: For next hot update we can test the changes and we can close this issue
