### ISSUE TITLE
Moving lessons left to right and right to left is not smooth

### ISSUE THREAD

**Issue by divyahariharan2103** [chimple/chimple#1771]
While Moving the lessons from left to right and vice versa the screen freezes for few seconds and does not move smoothly as expected.

**Comment by divyahariharan2103** [comment]
[Uploading... Lesson scrolling.mp4]

**Comment by divyahariharan2103** [comment]
https://images.zenhubusercontent.com/281200503/ce5b4972-32b8-47b7-9cbd-453b2d07681c/lesson_scrolling.mp4

**Comment by Pramodmarssun** [comment]
we can feel slowness when we scroll lesson cards, left to right and right to left 

https://user-images.githubusercontent.com/108517798/228118726-67e41f45-d92e-44e4-a3ba-6f71c926984d.mp4
