### ISSUE TITLE
Writing game issue

### ISSUE THREAD

**Issue by divyahariharan2103** [chimple/chimple#1781]
**Describe the bug**
In the tracing activity if there are long words present, the user is not able to trace the last few letters of the word as it is not completely visible on the mobile and tab screens.
And because of this issue the user will not be able to progress for further levels and complete the lesson.
![Screenshot_2023-03-28-11-10-18-014_org.chimple.cuba.jpg](https://images.zenhubusercontent.com/63d75b4c03fbfb55de1ee550/16a58227-d2c0-4aef-806d-9d9962f47400)
**To Reproduce**
1. Install the latest cuba app from the apk in mobile or tab.
2. Open the app and click on debug login button. 
3. In the home screen select 'English' subject in the header and choose Grade 2 in the grade dropdown.
4. In the unit dropdown select 'Unit 16' and play 'Days of the week' lesson.
5. In this lesson, in level 4 the issue can be observed. 

**Expected behavior**
The whole word should be visible on the mobile or tab screen and should be tracable.

**Smartphone (please complete the following information):**
 - Device: Lenovo tabs
 - OS: Android 9
**Additional context**

**Comment by Pramodmarssun** [comment]
I have tested the games 
It's working but audios are not playing in the games
