### ISSUE TITLE
UI enhancement- Text changes

### ISSUE THREAD

**Issue by akshattak** [chimple/chimple#1799]
- [x] Select App Language -> Choose your language
- [x] Enter your Phone Number -> Enter Mobile Number (10-digit)
- [x] Sent the OTP -> Send OTP
- [x] Please select your profile -> Select the child’s profile
- [x] Create New User -> Create New Child Profile
- [x] Enter Child Name -> What is your child’s name?
- [x] Select Child Gender -> What is your child’s gender?
- [x] Select Child Age -> What is your child’s age?
- [x] Select Child Avatar -> Choose an avatar for your child
- [x] Please create your child profile-> Choose your child’s class details
- [x] Enter the class code to join the class-> Enter the code your teacher has given to join the class
- [x] Error -> Invalid Code. Please contact your teacher

**Comment by akshattak** [comment]
Select App Language -> Choose your language
Enter your Phone Number -> Enter Mobile Number (10-digit)
Sent the OTP -> Send OTP
Please select your profile -> Select the child’s profile
Create New User -> Create New Child Profile
Enter Child Name -> What is your child’s name?
Select Child Gender -> What is your child’s gender?
Select Child Age -> What is your child’s age?
Select Child Avatar -> Choose an avatar for your child
Enter the code your teacher has given to join the class
Error -> Invalid Code. Please contact your teacher

**Comment by Pramodmarssun** [comment]
**Choose your child’s class details**  this texts are in white color

**Comment by Pramodmarssun** [comment]
**Choose your child’s class details** in this sentence "details" text is not there
