### ISSUE TITLE
"Lesson Played" is displaying as "Last Played" in leaderboard

### ISSUE THREAD

**Issue by pratapramesh** [chimple/chimple#1816]
- "Lesson Played" is displaying as "Last Played" in leaderboard and it should be display as "Lesson Played

![Screenshot_2023-07-28-15-24-07-615](https://github.com/chimple/chimple/assets/138564361/337ec848-f409-4890-a6c5-5374091f2c0e)

**Comment by Pramodmarssun** [comment]
This is fixed and we can move it to done
