### ISSUE TITLE
Character Place has to change for the following Games

### ISSUE THREAD

**Issue by Kiranks05** [chimple/chimple#375]
1. Multiply Beads
2. ask a problem
3. Sum together
4. write set
![Screenshot_2020-10-05-14-05-38-431_org chimple bahama](https://user-images.githubusercontent.com/57090054/95185829-db6a9580-07e6-11eb-8906-f18ac62efa56.jpg)
![Screenshot_2020-10-05-14-01-35-524_org chimple bahama](https://user-images.githubusercontent.com/57090054/95185849-e45b6700-07e6-11eb-956c-05b1f7f6b283.jpg)
![Screenshot_2020-10-05-13-41-20-575_org chimple bahama](https://user-images.githubusercontent.com/57090054/95185865-eae9de80-07e6-11eb-8fd9-7ca102c425c6.jpg)
![Screenshot_2020-10-06-15-13-38-362_org chimple bahama](https://user-images.githubusercontent.com/57090054/95185974-0e148e00-07e7-11eb-8d62-c3c7f3d29161.jpg)

**Comment by talapadi** [comment]
Fixed:

1. Multiply Beads
2. ask a problem

The other 2 are ok
