### ISSUE TITLE
Quiz literacy game - Touch is got disabled 

### ISSUE THREAD

**Issue by rani-12** [chimple/chimple#382]
![Screenshot_2020-10-07-08-23-46-76_ddc0fec0f25cadbb53407d57e5100bc9](https://user-images.githubusercontent.com/55230694/95284972-45357e80-087d-11eb-8d60-a507d709f544.png)
![quiz lit](https://user-images.githubusercontent.com/55230694/95285000-5aaaa880-087d-11eb-81d0-16e37611b5f9.PNG)
![quiz lit1](https://user-images.githubusercontent.com/55230694/95285014-639b7a00-087d-11eb-91ce-d7604d329803.PNG)

**Comment by shyamalu** [comment]
Hi Rani,
 I am not able to reproduce this issue. I had also sent a video to you

Thanks
