### ISSUE TITLE
Comparison- there is no randomization in right answer Option , everything is left aligned

### ISSUE THREAD

**Issue by Kiranks05** [chimple/chimple#659]
We need to shuffle the data around

![Screenshot_2020-11-04-17-27-38-102_org.chimple.bahama.jpg](https://user-images.githubusercontent.com/57090054/98110169-b12ef500-1ec4-11eb-8ccd-8a76539ff832.jpg)

**Comment by ashishkr04** [comment]
changes done in sheet.
