### ISSUE TITLE
In Parent Screen -Teachers name is not Displaying for the Student

### ISSUE THREAD

**Issue by vineet32** [chimple/chimple#695]
![Screenshot_20201109-161912](https://user-images.githubusercontent.com/67994324/98533393-efebf300-22a8-11eb-89a1-630153dc336d.png)

**Comment by shyamalupadhya** [comment]
<img width="1069" alt="Screenshot 2020-11-10 at 4 40 43 PM" src="https://user-images.githubusercontent.com/60498476/98666888-a5837880-2373-11eb-946a-e1371d46f1cc.png">
