### ISSUE TITLE
In first modification screen - While creating user in reward screen accessories are not loading

### ISSUE THREAD

**Issue by vineet32** [chimple/chimple#803]
![Screenshot_20201207-154849](https://user-images.githubusercontent.com/67994324/101340656-08e6c480-38a6-11eb-9601-802974f1f973.png)

**Comment by vineet32** [comment]
Still, i am seeing same issue here in this screen in today's APK

**Comment by talapadi** [comment]
It was fixed after the meeting. So the apk will not include this. Try tomorrow

**Comment by vineet32** [comment]
> 
> 
> It was fixed after the meeting. So the apk will not include this. Try tomorrow

ok boss
