### ISSUE TITLE
Background color clashes with font/elements

### ISSUE THREAD

**Issue by talapadi** [chimple/chimple#934]
Camp and Dog
Underwater and Dog
Underwater and hippo
Beach and bear
City and duck
Desert and camel
Camp and dog
Camp and hippo
Garden and duck

**Comment by Kiranks05** [comment]
![Screenshot_2021-02-23-16-45-32-806_org chimple bahama](https://user-images.githubusercontent.com/57090054/108836980-8d202c80-75f7-11eb-9340-63b04202c278.jpg)
![Screenshot_2021-02-23-16-42-48-262_org chimple bahama](https://user-images.githubusercontent.com/57090054/108837005-94dfd100-75f7-11eb-819f-caf78f2f867a.jpg)

**Comment by Kiranks05** [comment]
![Screenshot_2021-03-17-15-16-16-704_org chimple bahama](https://user-images.githubusercontent.com/57090054/111448083-18429d00-8734-11eb-9f42-897a8a419872.jpg)
![Screenshot_2021-03-17-15-17-48-287_org chimple bahama](https://user-images.githubusercontent.com/57090054/111448095-1973ca00-8734-11eb-9717-a7857b8280ad.jpg)
