### ISSUE TITLE
Dont show student in add_teacher popup if that student is already linked to that section

### ISSUE THREAD

**Issue by talapadi** [chimple/chimple#947]
https://github.com/chimple/malta/issues/861

Steps to reproduce:-

1. Have to create new student in CT as 'Aa', then from this student share the link.
2. from that shared link have to create user as 'aa' in chimple app and accept the teacher request and played lesson 'a' & 'b'.
3. Again same procedure follows in CT as 'Bb' and in chimple  app as 'bb'
4. Here, have to link with old user which had given name as 'aa', from same teacher, then just play only lesson 'a'
5. In progress table of CT in the student column 'Bb' will be flowing lesson 'a' & 'b' data.
6. ![IMG-20210128-WA0016](https://user-images.githubusercontent.com/67994324/106174934-88648600-61bb-11eb-8e95-f14150a5ce9b.jpg)
![IMG-20210128-WA0018](https://user-images.githubusercontent.com/67994324/106174927-869ac280-61bb-11eb-983f-e55e9f1156b2.jpg)
![IMG-20210128-WA0017](https://user-images.githubusercontent.com/67994324/106174931-88648600-61bb-11eb-870d-6d07983beac3.jpg)
![Screenshot_20210128-224830](https://user-images.githubusercontent.com/67994324/106174949-8bf80d00-61bb-11eb-8246-a9301d0d3fcb.png)

**Comment by vineet32** [comment]
its working & retesting done
