### ISSUE TITLE
Tick button on first-time character modification screen

### ISSUE THREAD

**Issue by akshattak** [chimple/chimple#968]

**Comment by Kiranks05** [comment]
the button doesn't look so proper
![Screenshot_2021-02-08-11-55-23-232_org chimple bahama](https://user-images.githubusercontent.com/57090054/107189301-2d2e6100-6a0f-11eb-959a-6a4f6a1f69fd.jpg)

**Comment by Kiranks05** [comment]
![Screenshot_2021-02-10-15-39-02-399_org chimple bahama](https://user-images.githubusercontent.com/57090054/107498856-47f10900-6bba-11eb-9582-30df79bc8789.jpg)
